#!/usr/bin/env bash
#
# Generates a syntactically-real wg-quick config to exercise Umbra's three
# import paths (paste, QR scan, .conf/.zip file) end to end. It is NOT a
# working VPN connection on its own: the [Peer] section is a locally
# generated placeholder keypair with a fake Endpoint, since this script has
# no real WireGuard server to talk to. Before using the output on-device,
# replace PrivateKey/PublicKey/Endpoint with the real values your VPN
# provider (or your own `wg genkey`'d server) gives you — everything else
# about the file (section names, field names, comma-separated AllowedIPs)
# is the real wg-quick format Umbra's WireGuardConfigStore parses.
#
# Usage: ./generate-example-config.sh [output-dir]
set -euo pipefail

if ! command -v wg >/dev/null 2>&1; then
    echo "error: 'wg' (wireguard-tools) not found on PATH." >&2
    echo "  Debian/Ubuntu: sudo apt install wireguard-tools" >&2
    echo "  macOS:         brew install wireguard-tools" >&2
    exit 1
fi

out_dir="${1:-./example-wg}"
mkdir -p "$out_dir"

client_private=$(wg genkey)
client_public=$(echo "$client_private" | wg pubkey)
# Placeholder only — there is no real server behind this key or endpoint.
server_public=$(wg genkey | wg pubkey)

conf_path="$out_dir/example.conf"
cat > "$conf_path" <<EOF
[Interface]
# Generated by generate-example-config.sh — a real client key, not a real tunnel.
PrivateKey = ${client_private}
Address = 10.66.66.2/32
DNS = 1.1.1.1

[Peer]
# PLACEHOLDER — replace with your actual VPN server's values before use.
PublicKey = ${server_public}
Endpoint = vpn.example.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
EOF
chmod 600 "$conf_path"
echo "Wrote $conf_path (client public key: ${client_public})"

zip_path="$out_dir/example.zip"
if command -v zip >/dev/null 2>&1; then
    (cd "$out_dir" && zip -q -j example.zip example.conf)
    echo "Wrote $zip_path (for the \"Import file\" zip path)"
else
    python3 - "$conf_path" "$zip_path" <<'PY'
import sys, zipfile
conf_path, zip_path = sys.argv[1], sys.argv[2]
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    z.write(conf_path, arcname="example.conf")
PY
    echo "Wrote $zip_path via python3 zipfile (for the \"Import file\" zip path)"
fi

if command -v qrencode >/dev/null 2>&1; then
    qr_path="$out_dir/example.conf.png"
    qrencode -t png -o "$qr_path" -r "$conf_path"
    echo "Wrote $qr_path (for the \"Scan QR\" path — display it on a second screen and scan with Umbra)"
else
    echo "note: 'qrencode' not found, skipping QR PNG — install it (apt/brew install qrencode) to also test \"Scan QR\""
fi

cat <<EOF

Before importing into Umbra: edit $conf_path and replace PublicKey/Endpoint
with your real VPN server's values (this script has no server to talk to,
so those two fields are placeholders). Then test any of Umbra's three
import paths against the same file:
  - paste:      open $conf_path in a text editor and paste its contents
  - file/zip:   WireGuard config screen -> Import file -> $zip_path
  - QR:         WireGuard config screen -> Scan QR -> scan example.conf.png
EOF
